### ISSUE TITLE
Admins receive "Invalid permissions" error when attempting to manually register device for user

### ISSUE THREAD

**Issue by nbebout** [onesimus-systems/packet-guardian#12]
I was trying to manually register a device for a user and receive an "Invalid permissions" error.  This happens for both helpdesk users and admin users, but it works fine when I manually register for my own account.

**Comment by lfkeitel** [comment]
File device.go in controllers/api, lines 44-49 need to be replaced with:

```go
if formUsername == sessionUser.Username {
	if sessionUser.Can(models.CreateOwn) {
		formUser = sessionUser
	} else {
		common.NewAPIResponse("Permission denied", nil).WriteResponse(w, http.StatusForbidden)
		return
	}
}
```

The control flow is wrong.
